### ISSUE TITLE
add list of maintained external plugins

### ISSUE THREAD

**Issue by doktordirk** [voidberg/awesome-aurelia#19]

**Comment by riddla** [comment]
We could add a link to my list over at http://aureliaholics.com/#/pluginlist. As the aurelia team has an official plugin registry, we should not double the effort. My list just fetches https://github.com/aurelia/registry.

**Comment by doktordirk** [comment]
the aurelia registry is as is just a registry. doesn't even show the description one liner. i rather thought of a list which has some bullet points of what the plugin can do. so one doesn't haev to click through all of them.
+s some of them, eg bs-model is even deprecated

**Comment by riddla** [comment]
My plan for the list on aureliaholics.com is to also scrape the descriptions from the different projects - would that be helpful for you?

**Comment by doktordirk** [comment]
that's a start at least. though, i really think a maintained list with bullet-point descriptions would be better. the one-liners don't say too much

**Comment by riddla** [comment]
Maybe something like http://ngmodules.org/ could be a good thing for the aurelia community. 
I'm strifing for something that the plugin users (and authors?) could maintain themselfs, because in my experience lists that are maintained "by hand" by only one or a few persons tend to get outdated quickly.

**Comment by doktordirk** [comment]
yeah, that one would be good. one liner + tags (+ badges from github?) + some stats. :+1:

**Comment by doktordirk** [comment]
ps: in that case all/most comes from github. so, i agree with who maintains

**Comment by doktordirk** [comment]
pps: that github thing reminds me of https://github.com/SpoonX/api-github. dunno if that's be any help

**Comment by RWOverdijk** [comment]
:+1: :)

**Comment by voidberg** [comment]
This repo has been merged into https://github.com/behzad888/awesome-aurelia

Can we please move the discussion here: https://github.com/behzad888/awesome-aurelia/issues ?
