### ISSUE TITLE
Wanna merge?

### ISSUE THREAD

**Issue by riddla** [voidberg/awesome-aurelia#2]
I just started my own awesome-aurelia list some days ago over at https://github.com/riddla/awesome-aurelia. Maybe you wanna integrate some of my links? I would happily deprecate my list and point people to yours after that.

**Comment by voidberg** [comment]
I'd really love more people helping on this so if you're game I'd love to give you access to this repo.

**Comment by webwurst** [comment]
:+1:

**Comment by riddla** [comment]
Oh, fine. I would gladly work within you repo and merge some of links in, when you give me the access.

**Comment by voidberg** [comment]
I've added you to the contributors list. Thanks!

**Comment by riddla** [comment]
Thanks a lot for adding me, I finally found the time for the merge (a53b10fcb9f4d6f1995eb68ae2d240d2a8a110b8) and set a pointer to your list at https://github.com/riddla/awesome-aurelia.
